apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: europe-central2-docker.pkg.dev/ticketing-dev-410110/ticketing-registry/auth:latest
          env:
            - name: DB_URI
              value: 'mongodb://auth-mongo-srv:27017/users'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: json-secret
                  key: JSON_WEB_TOKEN_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
