apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          # image: us.gcr.io/ticketing-dev-410110/expiration
          image: csaszargellert/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: ticketing-dev
            - name: NATS_SERVER_URL
              value: 'http://nats-srv:4222'
            - name: REDIS_URI
              value: redis-srv
