name: Deploy

on:
  push:
    branches:
      - 'master'
    paths: 
      - 'auth/**'

env:
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  CLUSTER_REGION: ${{ secrets.CLUSTER_REGION }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_REGISTRY: ${{ secrets.GOOGLE_REGISTRY }}
  GOOGLE_REGISTRY_REGION: ${{ secrets.REGISTRY_REGION }}
  

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        project_id: ${{ env.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true

    - name: Docker configuration and image build and image deploy
      run: |
        gcloud auth configure-docker "$GOOGLE_REGISTRY_REGION-docker.pkg.dev"
        docker build -t "$GOOGLE_REGISTRY_REGION-docker.pkg.dev/$GOOGLE_PROJECT/$GOOGLE_REGISTRY/auth:latest" ./auth
        docker push "$GOOGLE_REGISTRY_REGION-docker.pkg.dev/$GOOGLE_PROJECT/$GOOGLE_REGISTRY/auth:latest"        

    #- name: Deploy
     # run: |-
      #  kubectl rollout status deployment/$DEPLOYMENT_NAME
