name: Deploy

on:
  push:
    branches:
      - 'master'
    paths: 
      - 'auth/**'

env:
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  CLUSTER_REGION: ${{ secrets.CLUSTER_REGION }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_REGISTRY: ${{ secrets.GOOGLE_REGISTRY }}
  GOOGLE_REGISTRY_REGION: ${{ secrets.REGISTRY_REGION }}
  

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GOOGLE_REGISTRY_REGION-docker.pkg.dev
    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ env.CLUSTER_REGION }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          -t "$GOOGLE_REGISTRY_REGION-docker.pkg.dev/$GOOGLE_PROJECT/$GOOGLE_REGISTRY/auth:latest" ./auth
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "$GOOGLE_REGISTRY_REGION-docker.pkg.dev/$GOOGLE_PROJECT/$GOOGLE_REGISTRY/auth:latest"

    #- name: Deploy
     # run: |-
      #  kubectl rollout status deployment/$DEPLOYMENT_NAME
