name: Deploy manifests

on:
  push:
    branches:
      - 'master'
    paths:
      - 'infra/k8s-prod/**'

env:
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  CLUSTER_REGION: ${{ secrets.CLUSTER_REGION }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_REGISTRY: ${{ secrets.GOOGLE_REGISTRY }}
  GOOGLE_REGISTRY_REGION: ${{ secrets.REGISTRY_REGION }}

jobs:
  setup-apply:
    name: Setup And Apply
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - uses: simenandre/setup-gke-gcloud-auth-plugin@v1

      - name: Apply
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --region $CLUSTER_REGION --project $GOOGLE_PROJECT
          find ./infra/k8s-prod -type f -name '*.yaml' -exec sed -i "s/GOOGLE_REGISTRY_REGION/$GOOGLE_REGISTRY_REGION/g" {} \;
          find ./infra/k8s-prod -type f -name '*.yaml' -exec sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" {} \;
          find ./infra/k8s-prod -type f -name '*.yaml' -exec sed -i "s/GOOGLE_REGISTRY/$GOOGLE_REGISTRY/g" {} \;
          kubectl apply -f infra/k8s-prod
